name: Cloudflared Custom v3
version: 1.0
slug: cloudflared_custom_v3
description: "Cloudflared tunnel com network: host"
url: "https://github.com/RoCkE18/home-assistant-addons/tree/main/cloudflared_custom_v3"
startup: services
boot: auto
hassio_api: true
host_network: true

arch:
  - aarch64
  - amd64
  - armv7

options:
  tunnel_token: ""
  external_hostname: ""
  additional_hosts: []
  catch_all_service: ""

schema:
  tunnel_token: str
  external_hostname: str
  additional_hosts:
    - hostname: str
      service: str
  catch_all_service: str

environment:
  TUNNEL_TOKEN: "{tunnel_token}"

build_from:
  aarch64: "debian:bullseye-slim"
  amd64: "debian:bullseye-slim"
  armv7: "debian:bullseye-slim"
