name: Cloudflared Custom v2
version: 1.0
slug: cloudflared_custom_v2
description: "Cloudflared tunnel com network: host"
startup: services
boot: auto
hassio_api: true
host_network: true

options:
  tunnel_token: ""
  external_hostname: ""
  additional_hosts: []
  catch_all_service: ""

schema:
  tunnel_token: str
  external_hostname: str
  additional_hosts:
    - str
  catch_all_service: str

environment:
  TUNNEL_TOKEN: "{tunnel_token}"

#image: local/cloudflared_custom_v2

build_from:
  aarch64: "debian:bullseye-slim"
  amd64: "debian:bullseye-slim"
  armv7: "debian:bullseye-slim"
